
	CREATE PROCEDURE EliminarProducto
	 @Id AS UNIQUEIDENTIFIER
	  AS
	  BEGIN

	SET NOCOUNT ON;
	   BEGIN TRANSACTION
	DELETE
	FROM            Productos
	WHERE Productos.Id = @Id 
	SELECT @Id
COMMIT TRANSACTION

END